const projects = [
    {
        title: "GrappleRunner",
        description: "A 3D endless runner with a grapple hook",
        image: "images/dino_logo.png",
        github: "https://github.com/DinoInteractive/GrappleRunner",
        itch: "https://dinointeractive.itch.io/grapplerunner",
        tags: ["Game", "3D"],
    },
    {
        title: "Fundamental",
        description: "A simplistic platformer",
        image: "images/fundamental.png",
        github: "https://github.com/DinoInteractive/Fundamental",
        itch: "https://dinointeractive.itch.io/fundamental",
        tags: ["Game", "2D", "Platformer"],
    },
    {
        title: "Orbivore",
        description: "A glowing snake game",
        image: "images/orbivore.png",
        github: "",
        itch: "https://dinointeractive.itch.io/orbivore",
        tags: ["Game", "2D", "TopDown"],
    },
    {
        title: "Attack Of The Cubes",
        description: "A 4-way 2D shooter game",
        image: "images/aotc.png",
        github: "",
        itch: "https://dinointeractive.itch.io/attack-of-the-cubes-new",
        tags: ["Game", "2D", "TopDown"],
    },
    {
        title: "FroglightNotes",
        description: "A cross-platform notes app",
        image: "images/dino_logo.png",
        github: "https://github.com/DinoInteractive/FroglightNotes",
        itch: "https://dinointeractive.itch.io/froglightnotes",
        tags: ["Software"],
    },
    {
        title: "Fun File Explorer",
        description: "A semi game-like file explorer",
        image: "images/dino_logo.png",
        github: "https://github.com/DinoInteractive/fun_file_explorer",
        itch: "",
        tags: ["W.I.P", "Software"],
    }
]
